# This is a basic workflow to help you get started with Actions

name: Doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'docs/Doxyfile'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.PERSONAL_TOKEN}}
      # Now you can pass ${{ steps.buildnumber.outputs.build_number }} to the next steps.
      - name: Checkout New Branch
        run: |
          git fetch
          git checkout -b documentation-update-${{ steps.buildnumber.outputs.build_number }}
          git push origin documentation-update-${{ steps.buildnumber.outputs.build_number }}

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          # Working directory
          working-directory: 'docs/'
          # Path to Doxyfile
          doxyfile-path: './Doxyfile'
          # Generate latex documentation
          #enable-latex: # optional
          # Extra alpine packages for the build environment
          #additional-packages: # optional, default is
      - name: commit changes
        run: |
          git config --global user.name "ZigRazor"
          git config --global user.email "zigrazor@gmail.com"
          git add docs
          git commit -m "Updated Doxygen Documentation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: documentation-update-${{ steps.buildnumber.outputs.build_number }}

      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@1.3.1
        with:
          # A GitHub API token
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          # The head ref that should be pulled into base.
          head: documentation-update-${{ steps.buildnumber.outputs.build_number }}
          # The title of the pull request.
          title: Documentation Update
          # The base branch for the pull request. Defaults to master.
          #base: # optional
          # Whether this should be a draft PR.
          draft: false # optional
          # The body of the pull request.
          body: Automatic Documentation Update # optional
          # A comma-separated list of GitHub logins that should review this PR.
          #reviewers: #optional
